In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
diseases = ['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema',
       'Effusion', 'Emphysema', 'Fibrosis', 'Hernia', 'Infiltration', 'Mass',
       'Nodule', 'Pleural_Thickening', 'Pneumonia', 'Pneumothorax']


diseases_abbr = {'Atelectasis': 'At',
                'Cardiomegaly': 'Cd',
                'Effusion': 'Ef',
                'Infiltration': 'In',
                'Mass': 'M',
                'Nodule': 'N',
                'Pneumonia': 'Pa',
                'Pneumothorax': 'Px',
                'Consolidation': 'Co',
                'Edema': 'Ed',
                'Emphysema': 'Em',
                'Fibrosis': 'Fb',
                'Pleural_Thickening': 'PT',
                'Hernia': 'H'
                }

In [3]:
train_df_path ="/scratch/gobi2/projects/ml4h/datasets/NIH/split/July16/train.csv"
test_df_path = "/scratch/gobi2/projects/ml4h/datasets/NIH/split/July16/test.csv"
val_df_path = "/scratch/gobi2/projects/ml4h/datasets/NIH/split/July16/valid.csv"

val_df = pd.read_csv(val_df_path)
train_df = pd.read_csv(train_df_path)
test_df = pd.read_csv(test_df_path)

In [4]:
WholeData = test_df.append([val_df, train_df])

In [5]:
WholeData.head(10)

,Patient ID,Image Index,Finding Labels,Follow-up #,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,...,Infiltration,Mass,Nodule,Atelectasis,Pneumothorax,Pleural_Thickening,Pneumonia,Fibrosis,Edema,Consolidation
0,31,00000031_000.png,No Finding,0,71,F,PA,2992,2991,0.143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,33,00000033_000.png,Atelectasis|Cardiomegaly|Fibrosis,0,72,F,PA,2992,2745,0.143,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,34,00000034_000.png,Emphysema,0,74,M,PA,2048,2500,0.171,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,34,00000034_001.png,No Finding,1,76,M,PA,2500,2048,0.168,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,67,00000067_000.png,Fibrosis,0,62,F,PA,2992,2991,0.143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,67,00000067_001.png,Atelectasis,1,65,F,PA,2992,2991,0.143,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,67,00000067_002.png,No Finding,2,66,F,PA,2992,2991,0.143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,72,00000072_000.png,Atelectasis,0,67,F,PA,2450,2839,0.143,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,113,00000113_000.png,No Finding,0,73,M,PA,2992,2991,0.143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,113,00000113_001.png,Atelectasis|Cardiomegaly|Effusion,1,73,M,PA,2992,2991,0.143,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
print("Number of images:",len(WholeData) )
Whole =WholeData.groupby("Patient ID")
print("Number of unique patients:",len(Whole.count()) )

Number of images: 112120
Number of unique patients: 30805

In [7]:
WholeDataX =WholeData.groupby("Patient Gender")
WholeDataX_df = WholeDataX.describe()
WholeDataX_df

               Patient ID                                                   \
                    count          mean          std  min     25%      50%
Patient Gender
F                 48780.0  14065.620418  8542.724452  3.0  6869.0  13646.5
M                 63340.0  14562.604310  8288.950582  1.0  7621.0  14129.0

                                 Follow-up #            ... Edema       \
                    75%      max       count      mean  ...   75%  max
Patient Gender                                          ...
F               20398.0  30804.0     48780.0  8.167671  ...   0.0  1.0
M               20900.0  30805.0     63340.0  8.886486  ...   0.0  1.0

               Consolidation
                       count      mean       std  min  25%  50%  75%  max
Patient Gender
F                    48780.0  0.041021  0.198341  0.0  0.0  0.0  0.0  1.0
M                    63340.0  0.042090  0.200797  0.0  0.0  0.0  0.0  1.0

[2 rows x 176 columns]

In [8]:
dfWhole_Sex = WholeDataX_df["Patient ID"]['count']
total_CXP= dfWhole_Sex["F"]+dfWhole_Sex["M"]
Male_percent = 100*dfWhole_Sex["M"]/total_CXP
print("Male Percent:  ",Male_percent)

print("female Percent:  ",100*dfWhole_Sex["F"]/total_CXP)
print(total_CXP)

Male Percent:   56.49304316803425
female Percent:   43.50695683196575
112120.0

In [9]:
print("male",.8*59.2435184354535 + 0.1*(60.5638085309704  + 59.0778486127323))
print("0-20",.8*0.867946532699381 + 0.1*( 0.716705759708105 + 1.01912543773009))
print("40-60",.8*30.8726563200861 + 0.1*(32.3386326122839 + 30.6904911556074 ))

male 59.35898046273307
0-20 0.8679403459033244
40-60 31.001037432858013

In [10]:
WholeData['Patient Gender'].value_counts()

M    63340
F    48780
Name: Patient Gender, dtype: int64

In [11]:
WholeData_020= WholeData[(WholeData['Patient Age'] >= 0) & (WholeData['Patient Age'] <= 19)]
WholeData_2040= WholeData[(WholeData['Patient Age'] >= 20) & (WholeData['Patient Age'] <= 39)]
WholeData_4060= WholeData[(WholeData['Patient Age'] >= 40) & (WholeData['Patient Age'] <= 59)]
WholeData_6080= WholeData[(WholeData['Patient Age'] >= 60) & (WholeData['Patient Age'] <= 79)]
WholeData_80= WholeData[(WholeData['Patient Age'] >= 80) ]

In [16]:
totalAgeCXP = len(WholeData_020) +len(WholeData_2040)+len(WholeData_4060)+len(WholeData_6080)+len(WholeData_80)
print("'0-20' Percent:  ",100*len(WholeData_020)/totalAgeCXP)
print("'20-40' Percent:  ",100*len(WholeData_2040)/totalAgeCXP)
print("'40-60' Percent:  ",100*len(WholeData_4060)/totalAgeCXP)
print("'60-80' Percent:  ",100*len(WholeData_6080)/totalAgeCXP)
print("'80-' Percent:  ",100*len(WholeData_80)/totalAgeCXP)
6.086336068498038+25.96414555833036+43.825365679628966+23.11184445237246+1.0123082411701747

'0-20' Percent:   6.086336068498038
'20-40' Percent:   25.96414555833036
'40-60' Percent:   43.825365679628966
'60-80' Percent:   23.11184445237246
'80-' Percent:   1.0123082411701747

99.99999999999999

In [3]:
Eval5 = pd.read_csv("./results3/Eval5.csv")
Eval4= pd.read_csv("./results37/Eval4.csv")
Eval3 = pd.read_csv("./results60/Eval3.csv")
Eval2 = pd.read_csv("./results96/Eval2.csv")
Eval1 = pd.read_csv("./results33/Eval1.csv")

In [4]:
Evalall = Eval1[['label','auc']]

Evalall["auc2"]=Eval2['auc']
Evalall["auc3"]=Eval3['auc']
Evalall["auc4"]=Eval4['auc']
Evalall["auc5"]=Eval5['auc']
Evalall

                 label       auc      auc2      auc3      auc4      auc5
0          Atelectasis  0.813189  0.813237  0.807925  0.813946  0.820490
1         Cardiomegaly  0.915323  0.915635  0.912982  0.913231  0.918532
2        Consolidation  0.802681  0.808699  0.797153  0.792286  0.802736
3                Edema  0.919530  0.914941  0.910510  0.913719  0.918096
4             Effusion  0.871282  0.874872  0.875577  0.877139  0.876421
5            Emphysema  0.898255  0.892540  0.898492  0.899249  0.898285
6             Fibrosis  0.784019  0.796463  0.790666  0.776201  0.792166
7               Hernia  0.979785  0.978651  0.983505  0.975349  0.972773
8         Infiltration  0.722080  0.715917  0.708756  0.716912  0.719990
9                 Mass  0.833107  0.828394  0.836235  0.832034  0.817493
10              Nodule  0.766934  0.779727  0.783810  0.784166  0.782697
11  Pleural_Thickening  0.802867  0.817615  0.817516  0.811223  0.817381
12           Pneumonia  0.739988  0.761085  0.778372  0.753171  0.761790
13        Pneumothorax  0.879150  0.875534  0.874022  0.888785  0.875357

In [5]:
Evalall.mean(axis=0)

auc     0.837728
auc2    0.840951
auc3    0.841109
auc4    0.839101
auc5    0.841015
dtype: float64

In [6]:
print("NIH Mean of 14 aucs mean over 5 run:     ",round(Evalall.mean(axis=0).mean(),3))
print("NIH Confidence interval of 14 aucs mean over 5 run:   ",round(1.96 * Evalall.mean(axis=0).std()/np.sqrt(5),3))

NIH Mean of 14 aucs mean over 5 run:      0.84
NIH Confidence interval of 14 aucs mean over 5 run:    0.001

In [7]:
print("NIH Mean of auce per disease over 5 run:     ")
round(Evalall.mean(axis=1),3)

NIH Mean of auce per disease over 5 run:

0     0.814
1     0.915
2     0.801
3     0.915
4     0.875
5     0.897
6     0.788
7     0.978
8     0.717
9     0.829
10    0.779
11    0.813
12    0.759
13    0.879
dtype: float64

In [8]:
print("NIH Confidence interval of auce per disease over 5 run:     ")
round(1.96 * Evalall.std(axis=1)/ np.sqrt(5),3)

NIH Confidence interval of auce per disease over 5 run:

0     0.004
1     0.002
2     0.005
3     0.003
4     0.002
5     0.002
6     0.007
7     0.004
8     0.004
9     0.006
10    0.006
11    0.006
12    0.012
13    0.005
dtype: float64

In [25]:
Corr= pd.read_csv("./results/correlation_raw_NIH.csv") # updated
Corr

    Run    Sex_Co     Sex_P    Age_Co     Age_P
0  Run1  0.183634  0.529732  0.072984  0.554644
1  Run2  0.090127  0.759294 -0.035127  0.562159
2  Run3  0.256562  0.375930  0.068394  0.786321
3  Run4  0.413920  0.141209  0.054395  0.676137
4  Run5  0.426353  0.128463  0.188360  0.353405

In [27]:

Corr.mean(axis=0)

Sex_Co    0.274119
Sex_P     0.386926
Age_Co    0.069802
Age_P     0.586533
dtype: float64

In [28]:
1.96 * Corr.std(axis=0)/np.sqrt(5)

Sex_Co    0.127828
Sex_P     0.234526
Age_Co    0.069732
Age_P     0.141272
dtype: float64

In [30]:
Corr= pd.read_csv("./results/correlation_NIH.csv") # updated
round(Corr,3)

    Run  Sex_Co  Sex_P  Age_Co  Age_P
0  Run1   0.184  0.530   0.073  0.555
1  Run2   0.090  0.759  -0.035  0.562
2  Run3   0.257  0.376   0.068  0.786
3  Run4   0.414  0.141   0.054  0.676
4  Run5   0.426  0.128   0.188  0.353
5  Mean   0.274  0.387   0.070  0.587
6    CI   0.128  0.235   0.070  0.141

In [21]:
Corr= pd.read_csv("./results/correlation_raw_NIH.csv")

In [22]:
Corr

    Run    Sex_Co     Sex_P    Age_Co     Age_P
0  Run1  0.183634  0.529732  0.072984  0.554644
1  Run2  0.090127  0.759294 -0.035127  0.562159
2  Run3  0.256562  0.375930  0.068394  0.786321
3  Run4  0.413920  0.141209  0.054395  0.676137
4  Run5  0.426353  0.128463  0.188360  0.353405

In [23]:
Corr.mean(axis=0)

Sex_Co    0.274119
Sex_P     0.386926
Age_Co    0.069802
Age_P     0.586533
dtype: float64

In [24]:
1.96 * Corr.std(axis=0) / np.sqrt(5)

Sex_Co    0.127828
Sex_P     0.234526
Age_Co    0.069732
Age_P     0.141272
dtype: float64

In [25]:
Corr2 = Corr.copy()
Corr.loc['mean'] = Corr2.mean(axis=0)
Corr.loc['CI'] = 1.96 * Corr2.std(axis=0) / np.sqrt(5)

In [26]:
Corr

       Run    Sex_Co     Sex_P    Age_Co     Age_P
0     Run1  0.183634  0.529732  0.072984  0.554644
1     Run2  0.090127  0.759294 -0.035127  0.562159
2     Run3  0.256562  0.375930  0.068394  0.786321
3     Run4  0.413920  0.141209  0.054395  0.676137
4     Run5  0.426353  0.128463  0.188360  0.353405
mean   NaN  0.274119  0.386926  0.069802  0.586533
CI     NaN  0.127828  0.234526  0.069732  0.141272