## TPR confidence interval plots

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

diseases = ['Airspace Opacity', 'Atelectasis', 'Cardiomegaly',
       'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture',
       'Lung Lesion', 'No Finding', 'Pleural Effusion', 'Pleural Other',
       'Pneumonia', 'Pneumothorax', 'Support Devices']

diseases_abbr = {'Cardiomegaly': 'Cd',
                'Effusion': 'Ef',
                'Enlarged Cardiomediastinum': 'EC',
                'Lung Lesion': 'LL',
                'Atelectasis': 'A',
                'Pneumonia': 'Pa',
                'Pneumothorax': 'Px',
                'Consolidation': 'Co',
                'Edema': 'Ed',
                'Pleural Effusion': 'Ef',
                'Pleural Other': 'PO',
                'Fracture': 'Fr',
                'Support Devices': 'SD',
                'Airspace Opacity': 'AO',
                'No Finding': 'NF'
                }

## Percentages

In [2]:
train_df_path ="/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_train.csv"
test_df_path ="/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_test.csv"
val_df_path = "/scratch/gobi2/projects/ml4h/datasets/new_split/8-1-1/new_valid.csv"
val_df = pd.read_csv(val_df_path)
train_df = pd.read_csv(train_df_path)
test_df = pd.read_csv(test_df_path)

In [3]:
WholeData = test_df.append([val_df, train_df])

In [4]:
WholeData.head(20)

,subject_id,gender,path,view,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Airspace Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,10002559,M,train/p10002559/s01/view1_frontal.jpg,frontal,NaN,NaN,0.0,NaN,NaN,-1.0,NaN,-1.0,NaN,0.0,0.0,NaN,NaN,NaN
1,10002559,M,train/p10002559/s01/view2_lateral.jpg,lateral,NaN,NaN,0.0,NaN,NaN,-1.0,NaN,-1.0,NaN,0.0,0.0,NaN,NaN,NaN
2,10002559,M,train/p10002559/s01/view3_lateral.jpg,lateral,NaN,NaN,0.0,NaN,NaN,-1.0,NaN,-1.0,NaN,0.0,0.0,NaN,NaN,NaN
3,10002559,M,train/p10002559/s02/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN
4,10002559,M,train/p10002559/s02/view2_lateral.jpg,lateral,1.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN
5,10005858,F,train/p10005858/s01/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,10005858,F,train/p10005858/s02/view1_frontal.jpg,frontal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10005858,F,train/p10005858/s02/view2_lateral.jpg,lateral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10005858,F,train/p10005858/s02/view3_lateral.jpg,lateral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10006501,F,train/p10006501/s01/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10006501,F,train/p10006501/s01/view2_lateral.jpg,lateral,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,10008493,M,train/p10008493/s01/view1_frontal.jpg,frontal,NaN,NaN,NaN,1.0,NaN,NaN,NaN,-1.0,-1.0,NaN,1.0,NaN,NaN,NaN
12,10008493,M,train/p10008493/s01/view2_lateral.jpg,lateral,NaN,NaN,NaN,1.0,NaN,NaN,NaN,-1.0,-1.0,NaN,1.0,NaN,NaN,NaN
13,10011126,M,train/p10011126/s01/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,10011126,M,train/p10011126/s01/view2_lateral.jpg,lateral,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,10011126,M,train/p10011126/s02/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,10011126,M,train/p10011126/s02/view2_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,10011126,M,train/p10011126/s02/view3_lateral.jpg,lateral,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,10015129,F,train/p10015129/s01/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
19,10015129,F,train/p10015129/s01/view2_lateral.jpg,lateral,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print("Number of images:",len(WholeData) )
Whole =WholeData.groupby("subject_id")
print("Number of unique patients:",len(Whole.count()) )

Number of images: 371858
Number of unique patients: 65079

In [6]:
WholeDataX =WholeData.groupby("gender")
WholeDataX_df = WholeDataX.describe()
WholeDataX_df

       subject_id                                                      \
            count          mean           std         min         25%
gender
F        177853.0  1.499090e+07  2.883554e+06  10000032.0  12489621.0
M        194005.0  1.501641e+07  2.879538e+06  10000764.0  12493783.0

                                           No Finding       ... Fracture       \
               50%         75%         max      count mean  ...      75%  max
gender                                                      ...
F       14985054.0  17503573.0  19999987.0    72846.0  1.0  ...      1.0  1.0
M       15053729.0  17487765.0  19999442.0    68734.0  1.0  ...      1.0  1.0

       Support Devices
                 count      mean       std  min  25%  50%  75%  max
gender
F              36680.0  0.932361  0.267733 -1.0  1.0  1.0  1.0  1.0
M              52231.0  0.938044  0.257066 -1.0  1.0  1.0  1.0  1.0

[2 rows x 120 columns]

In [7]:
dfWhole_Sex = WholeDataX_df["subject_id"]['count']
total_CXP= dfWhole_Sex["F"]+dfWhole_Sex["M"]
Male_percent = 100*dfWhole_Sex["M"]/total_CXP
print("Male Percent:  ",Male_percent)

print("female Percent:  ",100*dfWhole_Sex["F"]/total_CXP)
print("#images",total_CXP)

Male Percent:   52.17179676112925
female Percent:   47.82820323887075
#images 371858.0

In [8]:
WholeData['gender'].value_counts()

M    194005
F    177853
Name: gender, dtype: int64

In [9]:
train_df_path ="/h/laleh/Desktop/PycharmProjects/Fairness/Nov7/Percentage/MIMIC/train.csv"
test_df_path ="/h/laleh/Desktop/PycharmProjects/Fairness/Nov7/Percentage/MIMIC/test.csv"
val_df_path = "/h/laleh/Desktop/PycharmProjects/Fairness/Nov7/Percentage/MIMIC/valid.csv"
val_df = pd.read_csv(val_df_path)
train_df = pd.read_csv(train_df_path)
test_df = pd.read_csv(test_df_path)
WholeData = test_df.append([val_df, train_df])

In [10]:
WholeDataX =WholeData.groupby("gender_x")
WholeDataX_df = WholeDataX.describe()
WholeDataX_df

         subject_id                                                      \
              count          mean           std         min         25%
gender_x
F          177853.0  1.499090e+07  2.883554e+06  10000032.0  12489621.0
M          194005.0  1.501641e+07  2.879538e+06  10000764.0  12493783.0

                                             No Finding       ...  \
                 50%         75%         max      count mean  ...
gender_x                                                      ...
F         14985054.0  17503573.0  19999987.0    72846.0  1.0  ...
M         15053729.0  17487765.0  19999442.0    68734.0  1.0  ...

         Support Devices      religion
                     75%  max    count mean std min 25% 50% 75% max
gender_x
F                    1.0  1.0      0.0  NaN NaN NaN NaN NaN NaN NaN
M                    1.0  1.0      0.0  NaN NaN NaN NaN NaN NaN NaN

[2 rows x 128 columns]

In [11]:
dfWhole_Sex = WholeDataX_df["subject_id"]['count']
total_CXP= dfWhole_Sex["F"]+dfWhole_Sex["M"]
Male_percent = 100*dfWhole_Sex["M"]/total_CXP
print("Male Percent:  ",Male_percent)

print("female Percent:  ",100*dfWhole_Sex["F"]/total_CXP)
print("#images",total_CXP)

Male Percent:   52.17179676112925
female Percent:   47.82820323887075
#images 371858.0

In [12]:
WholeData.head(10)

,subject_id,gender_x,path,view,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Airspace Opacity,Lung Lesion,Edema,...,Pleural Effusion,Pleural Other,Fracture,Support Devices,gender_y,age_decile,religion,race,insurance,marital_status
0,10002559,M,train/p10002559/s01/view1_frontal.jpg,frontal,NaN,NaN,0.0,NaN,NaN,-1.0,...,0.0,NaN,NaN,NaN,M,20-30,NaN,NaN,NaN,NaN
1,10002559,M,train/p10002559/s01/view2_lateral.jpg,lateral,NaN,NaN,0.0,NaN,NaN,-1.0,...,0.0,NaN,NaN,NaN,M,20-30,NaN,NaN,NaN,NaN
2,10002559,M,train/p10002559/s01/view3_lateral.jpg,lateral,NaN,NaN,0.0,NaN,NaN,-1.0,...,0.0,NaN,NaN,NaN,M,20-30,NaN,NaN,NaN,NaN
3,10002559,M,train/p10002559/s02/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,M,20-30,NaN,NaN,NaN,NaN
4,10002559,M,train/p10002559/s02/view2_lateral.jpg,lateral,1.0,NaN,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,M,20-30,NaN,NaN,NaN,NaN
5,10005858,F,train/p10005858/s01/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,F,50-60,NaN,WHITE,Other,SINGLE
6,10005858,F,train/p10005858/s02/view1_frontal.jpg,frontal,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,F,50-60,NaN,WHITE,Other,SINGLE
7,10005858,F,train/p10005858/s02/view2_lateral.jpg,lateral,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,F,50-60,NaN,WHITE,Other,SINGLE
8,10005858,F,train/p10005858/s02/view3_lateral.jpg,lateral,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,F,50-60,NaN,WHITE,Other,SINGLE
9,10006501,F,train/p10006501/s01/view1_frontal.jpg,frontal,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,F,60-70,NaN,WHITE,Other,MARRIED

In [13]:
WholeDataA =WholeData.groupby("age_decile")
WholeDataA_df = WholeDataA.describe()
total_CXR = WholeDataA_df["subject_id"]['count'].sum()
dfWhole_Age = WholeDataA_df["subject_id"]['count']
Age1 = round(100*(dfWhole_Age["0-10"]+dfWhole_Age["20-Oct"])/total_CXR,2)
Age2 = round(100*(dfWhole_Age["20-30"]+dfWhole_Age["30-40"])/total_CXR,2)
Age3 = round(100*(dfWhole_Age["40-50"]+dfWhole_Age["50-60"])/total_CXR,2)
Age4 = round(100*(dfWhole_Age["60-70"]+dfWhole_Age["70-80"])/total_CXR,2)
Age5 = round(100*(dfWhole_Age["80-90"]+dfWhole_Age[">=90"])/total_CXR,2)
print("0-20 Percent:  ",Age1)
print("20-40 Percent:  ",Age2)
print("40-60 Percent:  ",Age3)
print("60-80 Percent:  ",Age4)
print("80- Percent:  ",Age5)
Age1 + Age2 + Age3 + Age4 + Age5

0-20 Percent:   2.2
20-40 Percent:   19.51
40-60 Percent:   37.2
60-80 Percent:   34.12
80- Percent:   6.96

99.99

In [14]:
2.20+19.51+37.20+34.12+6.96

99.99

In [15]:
WholeDataI =WholeData.groupby("insurance")
WholeDataI_df = WholeDataI.describe()
total_CXR = WholeDataI_df["subject_id"]['count'].sum()
dfWhole_Ins = WholeDataI_df["subject_id"]['count']
Ins1 = 100*(dfWhole_Ins["Medicare"])/total_CXR
Ins2 = 100*(dfWhole_Ins["Medicaid"])/total_CXR
Ins3 = 100*(dfWhole_Ins["Other"])/total_CXR

print("Medicare Percent:  ",Ins1)
print("Medicaid Percent:  ",Ins2)
print("Other Percent:  ",Ins3)

46.07 + 8.98 + 44.95

Medicare Percent:   46.07218293015006
Medicaid Percent:   8.977604745468328
Other Percent:   44.95021232438161

100.0

In [16]:
WholeDataR =WholeData.groupby("race")
WholeDataR_df = WholeDataR.describe()
WholeDataR_df

                              subject_id                              \
                                   count          mean           std
race
AMERICAN INDIAN/ALASKA NATIVE      761.0  1.501666e+07  2.823667e+06
ASIAN                             8479.0  1.508827e+07  2.851218e+06
BLACK/AFRICAN AMERICAN           48595.0  1.497838e+07  2.896457e+06
HISPANIC/LATINO                  16760.0  1.498038e+07  2.887127e+06
OTHER                            10010.0  1.508103e+07  2.991056e+06
UNABLE TO OBTAIN                  1235.0  1.485215e+07  3.019839e+06
UNKNOWN                           9337.0  1.502137e+07  2.906217e+06
WHITE                           176837.0  1.501440e+07  2.877738e+06

                                                                               \
                                      min         25%         50%         75%
race
AMERICAN INDIAN/ALASKA NATIVE  10248673.0  12493668.0  14382048.0  18116591.0
ASIAN                          10005329.0  12567919.0  15206209.0  17651038.0
BLACK/AFRICAN AMERICAN         10000935.0  12468956.0  14936098.0  17479533.0
HISPANIC/LATINO                10011607.0  12373624.0  15056964.0  17421215.0
OTHER                          10003637.0  12408654.0  15014371.0  17792682.0
UNABLE TO OBTAIN               10014078.0  11933892.0  15095611.0  17649604.0
UNKNOWN                        10002804.0  12427999.0  15115424.0  17546877.0
WHITE                          10000032.0  12515419.0  15067471.0  17481338.0

                                          No Finding       ...  \
                                      max      count mean  ...
race                                                       ...
AMERICAN INDIAN/ALASKA NATIVE  19998198.0      239.0  1.0  ...
ASIAN                          19990563.0     2768.0  1.0  ...
BLACK/AFRICAN AMERICAN         19999287.0    20108.0  1.0  ...
HISPANIC/LATINO                19983948.0     7559.0  1.0  ...
OTHER                          19979173.0     3302.0  1.0  ...
UNABLE TO OBTAIN               19918338.0      269.0  1.0  ...
UNKNOWN                        19999987.0     1560.0  1.0  ...
WHITE                          19999733.0    54104.0  1.0  ...

                              Support Devices      religion                   \
                                          75%  max    count mean std min 25%
race
AMERICAN INDIAN/ALASKA NATIVE             1.0  1.0      0.0  NaN NaN NaN NaN
ASIAN                                     1.0  1.0      0.0  NaN NaN NaN NaN
BLACK/AFRICAN AMERICAN                    1.0  1.0      0.0  NaN NaN NaN NaN
HISPANIC/LATINO                           1.0  1.0      0.0  NaN NaN NaN NaN
OTHER                                     1.0  1.0      0.0  NaN NaN NaN NaN
UNABLE TO OBTAIN                          1.0  1.0      0.0  NaN NaN NaN NaN
UNKNOWN                                   1.0  1.0      0.0  NaN NaN NaN NaN
WHITE                                     1.0  1.0      0.0  NaN NaN NaN NaN


                              50% 75% max
race
AMERICAN INDIAN/ALASKA NATIVE NaN NaN NaN
ASIAN                         NaN NaN NaN
BLACK/AFRICAN AMERICAN        NaN NaN NaN
HISPANIC/LATINO               NaN NaN NaN
OTHER                         NaN NaN NaN
UNABLE TO OBTAIN              NaN NaN NaN
UNKNOWN                       NaN NaN NaN
WHITE                         NaN NaN NaN

[8 rows x 128 columns]

In [17]:
WholeDataR =WholeData.groupby("race")
WholeDataR_df = WholeDataR.describe()
total_CXR = WholeDataR_df["subject_id"]['count'].sum()
dfWhole_Race = WholeDataR_df["subject_id"]['count']
Rac1 = 100*(dfWhole_Race["WHITE"])/total_CXR
Rac2 = 100*(dfWhole_Race["BLACK/AFRICAN AMERICAN"])/total_CXR
Rac3 = 100*(dfWhole_Race["OTHER"])/total_CXR
Rac4 = 100*(dfWhole_Race["ASIAN"])/total_CXR
Rac5 = 100*(dfWhole_Race["HISPANIC/LATINO"])/total_CXR
Rac6 = 100*(dfWhole_Race["AMERICAN INDIAN/ALASKA NATIVE"])/total_CXR

print("WHITE Percent:  ",round( Rac1,2))
print("BLACK/AFRICAN AMERICAN Percent:  ",round(Rac2,2))
print("OTHER Percent:  ",round(Rac3,2))
print("ASIAN Percent:  ",round(Rac4,2))
print("HISPANIC/LATINO Percent:  ",round(Rac5,2))
print("AMERICAN INDIAN/ALASKA NATIVE Percent:  ",round(Rac6,2))
print("Unkhonwn or unable to obtain Percent:  ",round(100- (Rac1 + Rac2 + Rac3 +Rac4 + Rac5 + Rac6),2))

Rac1 + Rac2 + Rac3 +Rac4 + Rac5 + Rac6

WHITE Percent:   65.01
BLACK/AFRICAN AMERICAN Percent:   17.86
OTHER Percent:   3.68
ASIAN Percent:   3.12
HISPANIC/LATINO Percent:   6.16
AMERICAN INDIAN/ALASKA NATIVE Percent:   0.28
Unkhonwn or unable to obtain Percent:   3.89

96.11343533788703

## Subgroup-specific underdiagnosis rate

In [18]:
FP5_age = pd.read_csv("./results22/FP5_age.csv")
FP4_age = pd.read_csv("./results19/FP4_age.csv")
FP3_age = pd.read_csv("./results38/FP3_age.csv")
FP2_age = pd.read_csv("./results47/FP2_age.csv")
FP1_age = pd.read_csv("./results31/FP1_age.csv")
FP_age = FP1_age.append([FP2_age, FP3_age,FP4_age, FP5_age])
F_age_df = FP_age.describe()

In [19]:
print("FPR distribiution in ages")
print(round(F_age_df.loc['mean'],3))

FPR distribiution in ages
Unnamed: 0    0.000
60-80         0.116
40-60         0.271
20-40         0.264
80-           0.084
0-20          0.445
Name: mean, dtype: float64

In [20]:
round(1.96 * F_age_df.loc['std'] / np.sqrt(5),3)

Unnamed: 0    0.000
60-80         0.006
40-60         0.008
20-40         0.010
80-           0.008
0-20          0.028
Name: std, dtype: float64

In [21]:
FP5_race = pd.read_csv("./results22/FP5_race.csv")
FP4_race = pd.read_csv("./results19/FP4_race.csv")
FP3_race = pd.read_csv("./results38/FP3_race.csv")
FP2_race = pd.read_csv("./results47/FP2_race.csv")
FP1_race = pd.read_csv("./results31/FP1_race.csv")
FP_race = FP1_race.append([FP2_race, FP3_race,FP4_race, FP5_race])
F_race_df = FP_race.describe()

In [22]:
print("FPR distribiution in races")
print(round(F_race_df.loc['mean'],3))

FPR distribiution in races
Unnamed: 0    0.000
White         0.163
Black         0.249
Hisp          0.233
Other         0.195
Asian         0.213
American      0.166
Name: mean, dtype: float64

In [23]:
round(1.96 * F_race_df.loc['std'] / np.sqrt(5),3)

Unnamed: 0    0.000
White         0.007
Black         0.007
Hisp          0.011
Other         0.011
Asian         0.011
American      0.023
Name: std, dtype: float64

In [24]:
FP5_insurance = pd.read_csv("./results22/FP5_insurance.csv")
FP4_insurance = pd.read_csv("./results19/FP4_insurance.csv")
FP3_insurance = pd.read_csv("./results38/FP3_insurance.csv")
FP2_insurance = pd.read_csv("./results47/FP2_insurance.csv")
FP1_insurance = pd.read_csv("./results31/FP1_insurance.csv")
FP_insurance = FP1_insurance.append([FP2_insurance, FP3_insurance,FP4_insurance, FP5_insurance])
FP_insurance_df = FP_insurance.describe()

In [25]:
print("FPR distribiution in insurances")
print(round(FP_insurance_df.loc['mean'],3))

FPR distribiution in insurances
Unnamed: 0    0.000
Medicare      0.163
Other         0.179
Medicaid      0.307
Name: mean, dtype: float64

In [26]:
round(1.96 * FP_insurance_df.loc['std'] / np.sqrt(5),3)

Unnamed: 0    0.000
Medicare      0.006
Other         0.005
Medicaid      0.015
Name: std, dtype: float64

## Intersectional identity

In [27]:
FP5_InsSex = pd.read_csv("./results22/FP5_InsSex.csv")
FP4_InsSex = pd.read_csv("./results19/FP4_InsSex.csv")
FP3_InsSex = pd.read_csv("./results38/FP3_InsSex.csv")
FP2_InsSex = pd.read_csv("./results47/FP2_InsSex.csv")
FP1_InsSex = pd.read_csv("./results31/FP1_InsSex.csv")
FP_InsSex = FP1_InsSex.append([FP2_InsSex, FP3_InsSex,FP4_InsSex, FP5_InsSex])
FP_InSx =FP_InsSex.groupby("Insurance")

In [28]:
FP_InSx_df = FP_InSx.describe()

In [29]:
round(FP_InSx_df['M']['mean'],3)

Insurance
Medicaid    0.242
Medicare    0.171
Other       0.153
Name: mean, dtype: float64

In [30]:
round(1.96 * FP_InSx_df['M']["std"] / np.sqrt(5),3)

Insurance
Medicaid    0.009
Medicare    0.008
Other       0.007
Name: std, dtype: float64

In [31]:
round(FP_InSx_df['F']['mean'],3)

Insurance
Medicaid    0.362
Medicare    0.153
Other       0.225
Name: mean, dtype: float64

In [32]:
round(1.96 * FP_InSx_df['F']["std"] / np.sqrt(5),3)

Insurance
Medicaid    0.022
Medicare    0.006
Other       0.003
Name: std, dtype: float64

In [33]:
FP5_InsRace = pd.read_csv("./results22/FP5_InsRace.csv")
FP4_InsRace = pd.read_csv("./results19/FP4_InsRace.csv")
FP3_InsRace = pd.read_csv("./results38/FP3_InsRace.csv")
FP2_InsRace = pd.read_csv("./results47/FP2_InsRace.csv")
FP1_InsRace = pd.read_csv("./results31/FP1_InsRace.csv")
FP_InsRace = FP1_InsRace.append([FP2_InsRace, FP3_InsRace,FP4_InsRace, FP5_InsRace])
FP_InsRace =FP_InsRace.groupby("race")
FP_InRa_df =FP_InsRace.describe()

In [34]:
FP_InsRace.describe()

                              Unnamed: 0                                     \
                                   count mean  std  min  25%  50%  75%  max
race
AMERICAN INDIAN/ALASKA NATIVE        5.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
ASIAN                                5.0  4.0  0.0  4.0  4.0  4.0  4.0  4.0
BLACK/AFRICAN AMERICAN               5.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
HISPANIC/LATINO                      5.0  2.0  0.0  2.0  2.0  2.0  2.0  2.0
OTHER                                5.0  3.0  0.0  3.0  3.0  3.0  3.0  3.0
WHITE                                5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

                              Medicare            ...     Other            \
                                 count      mean  ...       75%       max
race                                              ...
AMERICAN INDIAN/ALASKA NATIVE      5.0  0.099167  ...  0.450382  0.450382
ASIAN                              5.0  0.113718  ...  0.240359  0.245114
BLACK/AFRICAN AMERICAN             5.0  0.276226  ...  0.185655  0.185655
HISPANIC/LATINO                    5.0  0.272246  ...  0.139174  0.146210
OTHER                              5.0  0.164050  ...  0.198668  0.211501
WHITE                              5.0  0.146499  ...  0.193128  0.199537

                              Medicaid                                \
                                 count      mean       std       min
race
AMERICAN INDIAN/ALASKA NATIVE      0.0       NaN       NaN       NaN
ASIAN                              5.0  0.353084  0.023461  0.312775
BLACK/AFRICAN AMERICAN             5.0  0.413591  0.020228  0.391602
HISPANIC/LATINO                    5.0  0.400643  0.031036  0.367565
OTHER                              5.0  0.316098  0.064733  0.219512
WHITE                              5.0  0.181956  0.015023  0.165391


                                    25%       50%       75%       max
race
AMERICAN INDIAN/ALASKA NATIVE       NaN       NaN       NaN       NaN
ASIAN                          0.359031  0.359031  0.360132  0.374449
BLACK/AFRICAN AMERICAN         0.395691  0.418453  0.421215  0.440994
HISPANIC/LATINO                0.367660  0.410686  0.427991  0.429314
OTHER                          0.290732  0.325854  0.358049  0.386341
WHITE                          0.173751  0.178895  0.186805  0.204939

[6 rows x 32 columns]

In [35]:
round(FP_InRa_df['Medicare']['mean'],3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.099
ASIAN                            0.114
BLACK/AFRICAN AMERICAN           0.276
HISPANIC/LATINO                  0.272
OTHER                            0.164
WHITE                            0.146
Name: mean, dtype: float64

In [36]:
round(1.96 * FP_InRa_df['Medicare']["std"] / np.sqrt(5),3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.029
ASIAN                            0.016
BLACK/AFRICAN AMERICAN           0.010
HISPANIC/LATINO                  0.011
OTHER                            0.007
WHITE                            0.006
Name: std, dtype: float64

In [37]:
round(FP_InRa_df['Medicaid']['mean'],3)

race
AMERICAN INDIAN/ALASKA NATIVE      NaN
ASIAN                            0.353
BLACK/AFRICAN AMERICAN           0.414
HISPANIC/LATINO                  0.401
OTHER                            0.316
WHITE                            0.182
Name: mean, dtype: float64

In [38]:
round(1.96 * FP_InRa_df['Medicaid']["std"] / np.sqrt(5),3)

race
AMERICAN INDIAN/ALASKA NATIVE      NaN
ASIAN                            0.021
BLACK/AFRICAN AMERICAN           0.018
HISPANIC/LATINO                  0.027
OTHER                            0.057
WHITE                            0.013
Name: std, dtype: float64

In [39]:
round(FP_InRa_df['Other']['mean'],3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.409
ASIAN                            0.230
BLACK/AFRICAN AMERICAN           0.182
HISPANIC/LATINO                  0.136
OTHER                            0.196
WHITE                            0.188
Name: mean, dtype: float64

In [40]:
round(1.96 * FP_InRa_df['Other']["std"] / np.sqrt(5),3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.033
ASIAN                            0.011
BLACK/AFRICAN AMERICAN           0.004
HISPANIC/LATINO                  0.008
OTHER                            0.009
WHITE                            0.008
Name: std, dtype: float64

In [41]:
FP5_RaceSex = pd.read_csv("./results22/FP5_RaceSex.csv")
FP4_RaceSex = pd.read_csv("./results19/FP4_RaceSex.csv")
FP3_RaceSex = pd.read_csv("./results38/FP3_RaceSex.csv")
FP2_RaceSex = pd.read_csv("./results47/FP2_RaceSex.csv")
FP1_RaceSex = pd.read_csv("./results31/FP1_RaceSex.csv")
FP_IRaceSex = FP1_RaceSex.append([FP2_RaceSex, FP3_RaceSex,FP4_RaceSex, FP5_RaceSex])
FP_RaceSex =FP_IRaceSex.groupby("race")
FP_RaceSex_df =FP_RaceSex.describe()

In [42]:
FP_RaceSex.describe()

                              Unnamed: 0                                     \
                                   count mean  std  min  25%  50%  75%  max
race
AMERICAN INDIAN/ALASKA NATIVE        5.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
ASIAN                                5.0  4.0  0.0  4.0  4.0  4.0  4.0  4.0
BLACK/AFRICAN AMERICAN               5.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
HISPANIC/LATINO                      5.0  2.0  0.0  2.0  2.0  2.0  2.0  2.0
OTHER                                5.0  3.0  0.0  3.0  3.0  3.0  3.0  3.0
WHITE                                5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

                                  M            ...                         F  \
                              count      mean  ...       75%       max count
race                                           ...
AMERICAN INDIAN/ALASKA NATIVE   5.0  0.190029  ...  0.214076  0.228739   5.0
ASIAN                           5.0  0.169280  ...  0.177724  0.182951   5.0
BLACK/AFRICAN AMERICAN          5.0  0.207096  ...  0.215540  0.215604   5.0
HISPANIC/LATINO                 5.0  0.117173  ...  0.125471  0.125608   5.0
OTHER                           5.0  0.206421  ...  0.211312  0.228716   5.0
WHITE                           5.0  0.177565  ...  0.184518  0.189396   5.0

                                                                       \
                                   mean       std       min       25%
race
AMERICAN INDIAN/ALASKA NATIVE  0.134815  0.032458  0.111111  0.111111
ASIAN                          0.269403  0.021068  0.249351  0.255584
BLACK/AFRICAN AMERICAN         0.275633  0.008413  0.261760  0.275699
HISPANIC/LATINO                0.459040  0.026124  0.430085  0.431850
OTHER                          0.160435  0.007849  0.148720  0.156436
WHITE                          0.138121  0.007248  0.129496  0.132970


                                    50%       75%       max
race
AMERICAN INDIAN/ALASKA NATIVE  0.111111  0.170370  0.170370
ASIAN                          0.260779  0.280519  0.300779
BLACK/AFRICAN AMERICAN         0.277248  0.279106  0.284351
HISPANIC/LATINO                0.469721  0.480226  0.483316
OTHER                          0.164153  0.164504  0.168362
WHITE                          0.139091  0.140902  0.148146

[6 rows x 24 columns]

In [43]:
round(FP_RaceSex_df['M']['mean'],3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.190
ASIAN                            0.169
BLACK/AFRICAN AMERICAN           0.207
HISPANIC/LATINO                  0.117
OTHER                            0.206
WHITE                            0.178
Name: mean, dtype: float64

In [44]:
round(1.96 * FP_RaceSex_df['M']["std"] / np.sqrt(5),3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.029
ASIAN                            0.010
BLACK/AFRICAN AMERICAN           0.008
HISPANIC/LATINO                  0.008
OTHER                            0.013
WHITE                            0.008
Name: std, dtype: float64

In [45]:
round(FP_RaceSex_df['F']['mean'],3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.135
ASIAN                            0.269
BLACK/AFRICAN AMERICAN           0.276
HISPANIC/LATINO                  0.459
OTHER                            0.160
WHITE                            0.138
Name: mean, dtype: float64

In [46]:
round(1.96 * FP_RaceSex_df['F']["std"] / np.sqrt(5),3)

race
AMERICAN INDIAN/ALASKA NATIVE    0.028
ASIAN                            0.018
BLACK/AFRICAN AMERICAN           0.007
HISPANIC/LATINO                  0.023
OTHER                            0.007
WHITE                            0.006
Name: std, dtype: float64

In [47]:
print(138+178)
print(190+135)

316
325

In [48]:
Eval5 = pd.read_csv("./results22/Eval5.csv")
Eval4 = pd.read_csv("./results19/Eval4.csv")
Eval3 = pd.read_csv("./results38/Eval3.csv")
Eval2 = pd.read_csv("./results47/Eval2.csv")
Eval1 = pd.read_csv("./results31/Eval1.csv")

In [49]:

Evalall = Eval1[['label','auc']]

Evalall["auc2"]=Eval2['auc']
Evalall["auc3"]=Eval3['auc']
Evalall["auc4"]=Eval4['auc']
Evalall["auc5"]=Eval5['auc']
Evalall

,label,auc,auc2,auc3,auc4,auc5
0,Airspace Opacity,0.784405,0.783839,0.781926,0.780642,0.781359
1,Atelectasis,0.837631,0.837549,0.836750,0.835749,0.835608
2,Cardiomegaly,0.829379,0.829341,0.826660,0.827601,0.828652
3,Consolidation,0.844549,0.845112,0.843367,0.843544,0.846124
4,Edema,0.905035,0.905858,0.904471,0.903695,0.904087
5,Enlarged Cardiomediastinum,0.760054,0.752302,0.759163,0.753896,0.763521
6,Fracture,0.719671,0.707227,0.717175,0.729794,0.711554
7,Lung Lesion,0.770842,0.779997,0.777454,0.767263,0.770030
8,No Finding,0.870459,0.869439,0.868266,0.868240,0.868174
9,Pleural Effusion,0.934543,0.933334,0.933444,0.932899,0.933343
10,Pleural Other,0.846678,0.844375,0.844465,0.850399,0.841581
11,Pneumonia,0.756371,0.752520,0.743133,0.744188,0.742865
12,Pneumothorax,0.904925,0.902275,0.904440,0.899509,0.902008
13,Support Devices,0.927627,0.927442,0.927050,0.926168,0.927368

In [50]:
Evala_dis =Evalall.groupby("label")

In [51]:
round(Evalall.mean(axis=0),3)

auc     0.835
auc2    0.834
auc3    0.833
auc4    0.833
auc5    0.833
dtype: float64

In [52]:
print("MIMIC Mean of 14 aucs mean over 5 run:     ",round(Evalall.mean(axis=0).mean(),3))
print("MIMIC Confidence interval of 14 aucs mean over 5 run:   ",round(1.96 * Evalall.mean(axis=0).std()/np.sqrt(5) ,3 ) )

MIMIC Mean of 14 aucs mean over 5 run:      0.834
MIMIC Confidence interval of 14 aucs mean over 5 run:    0.001

In [53]:
print("MIMIC Mean of auce per disease over 5 run:     ")
round(Evalall.mean(axis=1),3)

MIMIC Mean of auce per disease over 5 run:

0     0.782
1     0.837
2     0.828
3     0.845
4     0.905
5     0.758
6     0.717
7     0.773
8     0.869
9     0.934
10    0.845
11    0.748
12    0.903
13    0.927
dtype: float64

In [54]:
print("MIMIC Confidence interval of auce per disease over 5 run:     ")
round(1.96 * Evalall.std(axis=1)/ np.sqrt(5),3)

MIMIC Confidence interval of auce per disease over 5 run:

0     0.001
1     0.001
2     0.001
3     0.001
4     0.001
5     0.004
6     0.008
7     0.005
8     0.001
9     0.001
10    0.003
11    0.005
12    0.002
13    0.001
dtype: float64